name: keycloak-radius-plugin amd64, arm64, arm/v7
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: snapshot
        required: true
jobs:
  multi:
    runs-on: ubuntu-latest
    environment: Container Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: prepare insallation
        run: cd docker && rm -rf ./cli && cp -r ../cli ./cli

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/DockerfileMultiArch
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/donadio-org/keycloak-radius-plugin:${{ github.event.inputs.version }}-multiarch
            ghcr.io/donadio-org/keycloak-radius-plugin:latest-multiarch
